### ISSUE TITLE
Use destucturing assignment instead of copy&paste

### ISSUE THREAD

**Issue by ghost** [martiaaarti/Pokemon-Card#1]
https://github.com/martiaaarti/Pokemon-Card/blob/master/src/components/Details.js
`const countCandy = props.pokemon.candy_count ? props.pokemon.candy_count : "0";
`

**Comment by ghost** [comment]
Maybe create a stateless components instead of this repetition
"<h5 className='card-text mb-2'><b>Height:</b> {props.pokemon.height}</h5>"

**Comment by martiaaarti** [comment]
Solved.
